const FormData = [
    {
        type: 'text',
        name: 'First Name',
        label: 'First Name',
        id: 'First_Name',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'text',
        name: 'Last Name',
        label: 'Last Name',
        id: 'Last_Name',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'Number',
        name: 'Pincode',
        label: 'Pincode',
        id: 'Pincode',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'Number',
        name: 'Contact Number',
        label: 'Contact Number',
        id: 'Contact_Number',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'text',
        name: 'Address',
        label: 'Address',
        id: 'Address',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'text',
        name: 'Permanent Address',
        label: 'Permanent Address',
        id: 'Permanent_Address',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'Number',
        name: 'Student Id',
        label: 'Student Id',
        id: 'Student_Id',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'text',
        name: 'Subject',
        label: 'Subject',
        id: 'Subject',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
];
export default FormData;
